baseurl = "https://mrtctns.github.io/"
title = "Mert Çetin"
theme = ["hugo-embed-pdf-shortcode", "hugo-coder"]
enableInlineShortcodes = true
languagecode = "en"
relativeURLs = true
canonifyURLs = true
defaultcontentlanguage = "en"
[markup.goldmark.renderer]
unsafe = true

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Mert Çetin"

[params]
  author = "Mert ÇETİN"
  info = "iOS Developer"
  description = "Mert's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "mrtctns22@gmail.com"

  favicon_32 = "images/avatar.jpg"
  favicon_16 = "images/avatar.jpg"

  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 3
  url = "https://github.com/mrtctns"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/mrtctns/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/mertt_cetinn"
[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 3
  url = "https://medium.com/@mrtctns"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:mrtctns22@gmail.com"


# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url  = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url = "blog/"